"""add closed at to task

Revision ID: 2c0afdf11023
Revises: c7448ce7589e
Create Date: 2025-12-03 10:38:44.506928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c0afdf11023'
down_revision: Union[str, Sequence[str], None] = 'c7448ce7589e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('closed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'closed_at')
    # ### end Alembic commands ###
